### ISSUE TITLE
Bug Info.

### ISSUE THREAD

**Issue by huandney** [noobj2/Anki-Advanced-Review-Bottombar#14]
There are some types of notes that when I go to the info the following error occurs:
```
Debug Information:
Anki 2.1.35 (84dcaa86) Python 3.8.0 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2021-01-28 18:05:24

Caught exception:
Traceback (most recent call last):
  File "aqt\webview.py", line 37, in cmd
  File "aqt\webview.py", line 123, in _onCmd
  File "aqt\webview.py", line 547, in _onBridgeCmd
  File "<C:\Program Files\Anki\decorator.pyc:decorator-gen-78>", line 2, in linkHandler_wrap
  File "anki\hooks.py", line 638, in decorator_wrapper
  File "anki\hooks.py", line 635, in repl
  File "C:\Users\huand\AppData\Roaming\Anki2\addons21\880824023\main.py", line 147, in linkHandler
    return _old(self, url)
  File "<C:\Program Files\Anki\decorator.pyc:decorator-gen-34>", line 2, in linkHandler_wrap
  File "anki\hooks.py", line 638, in decorator_wrapper
  File "anki\hooks.py", line 635, in repl
  File "C:\Users\huand\AppData\Roaming\Anki2\addons21\153625306\main.py", line 240, in linkHandler
    return _old(self, url)
  File "C:\Users\huand\AppData\Roaming\Anki2\addons21\1136455830\Bottom_Bar.py", line 75, in linkHandler_wrap
    Card_Info._cs.toggle()
  File "C:\Users\huand\AppData\Roaming\Anki2\addons21\1136455830\Card_Info.py", line 72, in toggle
    self.show()
  File "C:\Users\huand\AppData\Roaming\Anki2\addons21\1136455830\Card_Info.py", line 61, in show
    self._update()
  File "C:\Users\huand\AppData\Roaming\Anki2\addons21\1136455830\Card_Info.py", line 384, in _update
    txt += d.cardStats_mod(current_card)
  File "C:\Users\huand\AppData\Roaming\Anki2\addons21\1136455830\Card_Info.py", line 320, in cardStats_mod
    return CardStats(self, card).report_mod()
  File "C:\Users\huand\AppData\Roaming\Anki2\addons21\1136455830\Card_Info.py", line 222, in report_mod
    self.addLine("Created", time.strftime("%Y-%m-%d | %H:%M", time.localtime(c.id/1000)))
OSError: [Errno 22] Invalid argument
```

![image](https://user-images.githubusercontent.com/19948348/106278395-0a32ce80-6211-11eb-8660-8a611f4f812f.png)

**Comment by noobj2** [comment]
Some people have reported this. but it happens really rarely
I'll try to work on it as soon as I can -_-

**Comment by noobj2** [comment]
Hi
I've been trying to update my add-ons. about this bug, I can't really reproduce it and I don't know what's causing it
did some googling and found [this ](https://bugs.python.org/issue29097). One user says "Sounds like it really is an OSError (that is, that the Windows OS is the source of the error).  Whether or not we can or should do something about that is a separate question, though."
I think this error happens really rarely (I haven't encountered it even once -_-) so I'm gonna close this issue.
However, if it happens regularly, I'd really appreciate it if you told me how to reproduce it.

**Comment by huandney** [comment]
Sorry, I only saw your reply after a long time.
I will be posting a deck with two cards where the error occurs:

https://drive.google.com/file/d/1R3tmGPjwq3ZsH4_smGlMoAf59gPmnuqG/view?usp=sharing

**Comment by huandney** [comment]
The error that happened was not from your addon, but from invalid card IDs:
https://forums.ankiweb.net/t/issue-with-huge-card-ids/12165
This addon fixed the problem:
https://ankiweb.net/shared/info/196231552
