### ISSUE TITLE
A but after the latest update

### ISSUE THREAD

**Issue by Naimdev** [noobj2/Anki-Advanced-Review-Bottombar#18]
After the latest update, this error occurs in some notes:

```
Debug info:
Anki 2.1.26 (70784154) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 10
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2021-07-29 20:19:41

Caught exception:
Traceback (most recent call last):
  File "aqt\webview.py", line 464, in handler
  File "aqt\reviewer.py", line 540, in _onTypedAnswer
  File "aqt\reviewer.py", line 243, in _showAnswer
  File "<D:\Program Files\Anki\decorator.pyc:decorator-gen-18>", line 2, in _showEaseButtons
  File "lib\site-packages\anki\hooks.py", line 638, in decorator_wrapper
  File "lib\site-packages\anki\hooks.py", line 629, in repl
  File "aqt\reviewer.py", line 598, in _showEaseButtons
  File "C:\Users\N\AppData\Roaming\Anki2\addons21\1136455830\Button_Colors.py", line 188, in _answerButtons
    for ease, label in self._answerButtonList():
  File "C:\Users\N\AppData\Roaming\Anki2\addons21\1136455830\Button_Colors.py", line 57, in _answerButtonList
    again = ((1, " {} ".format(again)),)
UnboundLocalError: local variable 'again' referenced before assignment
```
![Screenshot 2021-07-30 101431](https://user-images.githubusercontent.com/25878614/127631016-c542698a-dd5e-4385-957e-5a3f8db76a46.png)

Could you please provide me the previous version. Much appreciated, thank you.

**Comment by noobj2** [comment]
Hi
thank you for the report :D
Update the add-on, it should be fixed now

**Comment by Naimdev** [comment]
The update solved it, thank you so freaking much!

**Comment by noobj2** [comment]
<3
