### ISSUE TITLE
Add-on Error

### ISSUE THREAD

**Issue by jjgerr** [noobj2/Anki-Advanced-Review-Bottombar#26]
(Copying over from AnkiWeb)

Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.47 (dc156f34) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Mac 10.16
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2021-09-15 10:03:36
Add-ons possibly involved: ⁨Advanced Review Bottom Bar⁩

Caught exception:
Traceback (most recent call last):
  File "/Users.../Library/Application Support/Anki2/addons21/1136455830/Settings.py", line 2505, in open_settings
    settings = SettingsMenu()
  File "/Users.../Library/Application Support/Anki2/addons21/1136455830/Settings.py", line 482, in __init__
    self.mainWindow()
  File "/Users.../Library/Application Support/Anki2/addons21/1136455830/Settings.py", line 510, in mainWindow
    self.createNinthTab()
  File "/Users.../Library/Application Support/Anki2/addons21/1136455830/Settings.py", line 1929, in createNinthTab
    self.loadChaneLog()
  File "/Users.../Library/Application Support/Anki2/addons21/1136455830/Settings.py", line 1946, in loadChaneLog
    with open(file, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Users.../Library/Application Support/Anki2/addons21/1136455830\\changelog.html'

**Comment by noobj2** [comment]
hey
can you download this add-on and test if it works on your pc?
https://gofile.io/d/1w1JF7

**Comment by jjgerr** [comment]
unfortunately still getting the same error

**Comment by noobj2** [comment]
delete the ARBb add-on that you have installed. then close anki
and then try this one see if it works -_-
https://gofile.io/d/liNcjq

**Comment by jjgerr** [comment]
Still getting an error :(. I appreciate you trying to fix it!

Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.47 (dc156f34) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Mac 10.16
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2021-09-17 15:14:21
Add-ons possibly involved: ⁨Advanced Review Bottombar⁩

Caught exception:
Traceback (most recent call last):
  File "/Users/Library/Application Support/Anki2/addons21/1136455830/Settings.py", line 2506, in open_settings
    settings = SettingsMenu()
  File "/Users/Library/Application Support/Anki2/addons21/1136455830/Settings.py", line 482, in __init__
    self.mainWindow()
  File "/Users/Library/Application Support/Anki2/addons21/1136455830/Settings.py", line 510, in mainWindow
    self.createNinthTab()
  File "/Users/Library/Application Support/Anki2/addons21/1136455830/Settings.py", line 1929, in createNinthTab
    self.loadChaneLog()
  File "/Users/Library/Application Support/Anki2/addons21/1136455830/Settings.py", line 1947, in loadChaneLog
    with open(file, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/Library/Application Support/Anki2/addons21/1136455830\\changelog.html'

**Comment by noobj2** [comment]
ok, try this one -_-
https://gofile.io/d/vD3CDe
I really appreciate you helping -\_-

**Comment by nmeed** [comment]
This one works. Nice!

**Comment by noobj2** [comment]
hmmm, it's a bit weird. but I'll take it -_- I'm happy it works
