### ISSUE TITLE
Conflicts with Incremental Reading v4.10.3 when clicking Show Answer 

### ISSUE THREAD

**Issue by luzhe610** [noobj2/Anki-Advanced-Review-Bottombar#27]
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.47 (dc156f34) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2021-09-18 12:21:44

Caught exception:
Traceback (most recent call last):
  File "aqt\webview.py", line 541, in handler
  File "aqt\reviewer.py", line 701, in _onTypedAnswer
  File "aqt\reviewer.py", line 381, in _showAnswer
  File "aqt\reviewer.py", line 756, in _showEaseButtons
  File "C:\Users\lenovo\AppData\Roaming\Anki2\addons21\1136455830\Button_Colors.py", line 189, in _answerButtons
    buf += but(ease, label)
  File "C:\Users\lenovo\AppData\Roaming\Anki2\addons21\1136455830\Button_Colors.py", line 124, in but
    due_plain = self._buttonTime(i)
  File "decorator.py", line 232, in fun
  File "anki\hooks.py", line 89, in decorator_wrapper
  File "anki\hooks.py", line 86, in repl
TypeError: buttonTime() got multiple values for argument '_old'

**Comment by noobj2** [comment]
it's not caused by ARBb. You can test it by disabling all add-ons and leaving incremental reading enabled. you'll get the same error.
