### ISSUE TITLE
Unsupported operand type

### ISSUE THREAD

**Issue by GrimPixel** [noobj2/Anki-Advanced-Review-Bottombar#32]
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.50 (81cc5a09) Python 3.10.2 Qt 5.15.2 PyQt 5.15.6
Platform: Linux
Flags: frz=False ao=True sv=2
Add-ons, last update check: 2022-01-29 14:16:54
Add-ons possibly involved: ⁨Advanced Review Bottom Bar, Replay buttons on card, Open linked pdf docx epub audiovideo etc in external Program⁩

Caught exception:
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/aqt/webview.py", line 41, in cmd
    return json.dumps(self.onCmd(str))
  File "/usr/lib/python3.10/site-packages/aqt/webview.py", line 148, in _onCmd
    return self._onBridgeCmd(str)
  File "/usr/lib/python3.10/site-packages/aqt/webview.py", line 602, in _onBridgeCmd
    return self.onBridgeCmd(cmd)
  File "/usr/lib/python3.10/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/usr/lib/python3.10/site-packages/anki/hooks.py", line 89, in decorator_wrapper
    return repl(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/anki/hooks.py", line 86, in repl
    return new(_old=old, *args, **kwargs)
  File "/home/grim/.local/share/Anki2/addons21/879473266/reviewer.py", line 14, in myLinkHandler
    return _old(self, url)
  File "/usr/lib/python3.10/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/usr/lib/python3.10/site-packages/anki/hooks.py", line 89, in decorator_wrapper
    return repl(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/anki/hooks.py", line 86, in repl
    return new(_old=old, *args, **kwargs)
  File "/home/grim/.local/share/Anki2/addons21/879473266/linked__view.py", line 24, in myLinkHandler
    return _old(self, url)
  File "/home/grim/.local/share/Anki2/addons21/498789867/__init__.py", line 103, in review_link_handler_wrapper
    original_review_link_handler(reviewer, url)
  File "/home/grim/.local/share/Anki2/addons21/1136455830/Bottom_Bar.py", line 94, in linkHandler_wrap
    Card_Info._cs.toggle()
  File "/home/grim/.local/share/Anki2/addons21/1136455830/Card_Info.py", line 72, in toggle
    self.show()
  File "/home/grim/.local/share/Anki2/addons21/1136455830/Card_Info.py", line 61, in show
    self._update()
  File "/home/grim/.local/share/Anki2/addons21/1136455830/Card_Info.py", line 384, in _update
    txt += d.cardStats_mod(current_card)
  File "/home/grim/.local/share/Anki2/addons21/1136455830/Card_Info.py", line 320, in cardStats_mod
    return CardStats(self, card).report_mod()
  File "/home/grim/.local/share/Anki2/addons21/1136455830/Card_Info.py", line 265, in report_mod
    pressed_all = pressed_again + pressed_hard + pressed_good + pressed_easy
TypeError: unsupported operand type(s) for +: 'NoneType' and 'NoneType'

**Comment by noobj2** [comment]
hey
can you tell me the steps to get this error? 
I installed anki 2.1.50 (both qt5 and qt6) but, reviewed some cards while info bar was open didn't get the error. Tried creating a new profile and doing the same thing, didn't get the error again. Tried installing the other add-ons that were in the error report and doing the same thing, and again didn't get the error.

and also it'd be nice to have your settings (so I could have the exact settings as you when I try to get the error). To get the settings file go to ARBb settings menu and press "Create backup" button and send me the file that it creates.
