### ISSUE TITLE
anki.errors.NotFoundError

### ISSUE THREAD

**Issue by GregMpour** [noobj2/Anki-Advanced-Review-Bottombar#37]
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.

Debug info:
Anki 2.1.52 (9fe3588e) Python 3.10.4 Qt 5.15.2 PyQt 5.15.6
Platform: Linux
Flags: frz=False ao=True sv=2
Add-ons, last update check: 2022-05-23 18:09:25
Add-ons possibly involved: ⁨Advanced Review Bottom Bar⁩

Caught exception:
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/aqt/webview.py", line 42, in cmd
    return json.dumps(self.onCmd(str))
  File "/usr/lib/python3.10/site-packages/aqt/webview.py", line 149, in _onCmd
    return self._onBridgeCmd(str)
  File "/usr/lib/python3.10/site-packages/aqt/webview.py", line 619, in _onBridgeCmd
    return self.onBridgeCmd(cmd)
  File "/home/greg/.local/share/Anki2/addons21/1136455830/Bottom_Bar.py", line 94, in linkHandler_wrap
    Card_Info._cs.toggle()
  File "/home/greg/.local/share/Anki2/addons21/1136455830/Card_Info.py", line 77, in toggle
    self.show()
  File "/home/greg/.local/share/Anki2/addons21/1136455830/Card_Info.py", line 66, in show
    self._update()
  File "/home/greg/.local/share/Anki2/addons21/1136455830/Card_Info.py", line 394, in _update
    card2 = r.lastCard()
  File "/usr/lib/python3.10/site-packages/aqt/reviewer.py", line 157, in lastCard
    return self.mw.col.get_card(self._answeredIds[-1])
  File "/usr/lib/python3.10/site-packages/anki/collection.py", line 410, in get_card
    return Card(self, id)
  File "/usr/lib/python3.10/site-packages/anki/cards.py", line 60, in __init__
    self.load()
  File "/usr/lib/python3.10/site-packages/anki/cards.py", line 68, in load
    card = self.col._backend.get_card(self.id)
  File "/usr/lib/python3.10/site-packages/anki/_backend/generated.py", line 1800, in get_card
    raw_bytes = self._run_command(14, 0, message.SerializeToString())
  File "/usr/lib/python3.10/site-packages/anki/_backend/__init__.py", line 146, in _run_command
    raise backend_exception_to_pylib(err)
anki.errors.NotFoundError

**Comment by noobj2** [comment]
hey
I've been really busy lately and haven't updated the add-on. 
the issue might be because of an anki update. I'll try and look into it and fix it in the next update

**Comment by noobj2** [comment]
I started updating the add-so I updated Anki to 2.1.54 and the add-on seems to be working fine.
I couldn't replicate the error, can you tell me the steps to replicate the error?

**Comment by noobj2** [comment]
I'm going to close this issue, 
if you still have this issue, open it again by replying the steps to replicate the issue.
