### ISSUE TITLE
Error Anki 23.10, works otherwise fine cant adjust settings

### ISSUE THREAD

**Issue by ShawnO33** [noobj2/Anki-Advanced-Review-Bottombar#76]
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 23.10 (51a10f09) Python 3.9.15 Qt 6.5.3 PyQt 6.5.3
Platform: macOS-14.0-arm64-arm-64bit
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-11-04 09:09:39
Add-ons possibly involved: ⁨Advanced Review Bottom Bar⁩

Caught exception:
Traceback (most recent call last):
  File "/Users/User1/Library/Application Support/Anki2/addons21/1136455830/Settings.py", line 2790, in open_settings
    settings = SettingsMenu()
  File "/Users/User1/Library/Application Support/Anki2/addons21/1136455830/Settings.py", line 493, in __init__
    self.mainWindow()
  File "/Users/User1/Library/Application Support/Anki2/addons21/1136455830/Settings.py", line 513, in mainWindow
    self.createFirstTab()
  File "/Users/User1/Library/Application Support/Anki2/addons21/1136455830/Settings.py", line 800, in createFirstTab
    self.tab1.setAlignment(Qt.AlignHCenter)
AttributeError: type object 'Qt' has no attribute 'AlignHCenter'

**Comment by noobj2** [comment]
Fixed.
